require 'Items/ProceduralDistributions'
require "Items/ItemPicker"

-- Gunstore
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookAiming1");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 10);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookAiming2");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 8);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookAiming3");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 6);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookAiming4");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 4);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookAiming5");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 2);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookReloading1");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 10);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookReloading2");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 8);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookReloading3");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 6);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookReloading4");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 4);
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, "Base.BookReloading5");
table.insert(ProceduralDistributions["list"]["GunStoreLiterature"].items, 2);

-- Hunting
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookAiming1");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 1);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookAiming2");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.8);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookAiming3");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.6);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookAiming4");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.4);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookAiming5");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.2);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookReloading1");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 1);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookReloading2");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.8);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookReloading3");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.6);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookReloading4");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.4);
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, "Base.BookReloading5");
table.insert(ProceduralDistributions["list"]["HuntingLockers"].items, 0.2);

-- Police
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookAiming1");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 1);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookAiming2");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.8);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookAiming3");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.6);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookAiming4");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.4);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookAiming5");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.2);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookReloading1");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 1);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookReloading2");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.8);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookReloading3");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.6);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookReloading4");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.4);
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, "Base.BookReloading5");
table.insert(ProceduralDistributions["list"]["PoliceLockers"].items, 0.2);

-- Surplus
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookAiming1");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 10);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookAiming2");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 8);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookAiming3");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 6);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookAiming4");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 4);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookAiming5");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 2);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookReloading1");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 10);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookReloading2");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 8);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookReloading3");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 6);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookReloading4");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 4);
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, "Base.BookReloading5");
table.insert(ProceduralDistributions["list"]["ArmySurplusLiterature"].items, 2);

-- Trapper
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookAiming1");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 1);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookAiming2");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.8);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookAiming3");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.6);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookAiming4");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.4);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookAiming5");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.2);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookReloading1");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 1);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookReloading2");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.8);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookReloading3");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.6);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookReloading4");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.4);
table.insert(ProceduralDistributions["list"]["Trapper"].items, "Base.BookReloading5");
table.insert(ProceduralDistributions["list"]["Trapper"].items, 0.2);
